# name: Event-Based Workflow
 
# on:

#   # Trigger the workflow on push to the main branch
 
#   push:
    
#     branches:

#       - master

#     # Trigger on any tag push

#     tags:

#       - 'v*'  # Triggers on any tag starting with 'v' (e.g., v1.0.0)
 
#   # Trigger the workflow on a pull request to the main branch

#   pull_request:

#     branches:

#       - master
 
#   # Trigger the workflow on issue comment event

#   issue_comment:

#     types: [created]
 
#   # Trigger the workflow on a release event

#   release:

#     types: [created]
 
#   # Trigger the workflow on a cron schedule (runs every day at midnight UTC)

#   schedule:

#     - cron: '* * * * *'  # This will trigger at midnight UTC every day
 
# jobs:

#   run_echo_commands:

#     runs-on: ubuntu-latest
 
#     steps:

#       # Checkout the code

#       - name: Checkout code

#         uses: actions/checkout@v3
 
#       # Triggered by a push to the main branch

#       - name: Echo on push to main

#         if: github.event_name == 'push' && github.ref == 'refs/heads/master'

#         run: |

#           echo "This is a push event to the main branch!"
 
#       # Triggered by a push event for a tag (e.g., v1.0.0)

#       - name: Echo on tag push

#         if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

#         run: |

#           echo "A new tag was pushed: ${{ github.ref }}"
 
#       # Triggered by a pull request to the main branch

#       - name: Echo on pull request to main
     
#         if: github.event_name == 'pull_request' && github.ref == 'refs/heads/master'
#         run: |
#           echo "This is a pull request event to the main branch!"

 
#       # Triggered when an issue comment is created

#       - name: Echo on issue comment

#         if: github.event_name == 'issue_comment' && github.event.action == 'created'

#         run: |

#           echo "An issue comment was created: ${{ github.event.comment.body }}"
 
#       # Triggered when a release is created

#       - name: Echo on release creation

#         if: github.event_name == 'release' && github.event.action == 'created'

#         run: |

#           echo "A new release was created with the tag: ${{ github.event.release.tag_name }}"
 
#       # Triggered by a scheduled cron event (daily at midnight UTC)

#       - name: Echo on cron event

#         if: github.event_name == 'schedule'

#         run: |

#           echo "This is a scheduled event triggered by the cron schedule!"


name: Events Trigger Workflow

on:
  push:                  # Trigger on push events
    branches:
      - master
  pull_request:          # Trigger on pull request events
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:     # Manual trigger
    inputs:
      name:
        description: 'Name to greet'
        required: false
        default: 'Pritam'
  schedule:              # Scheduled trigger (every minute for testing)
    - cron: '* * * * *'
  check_run:             # Trigger for specific webhook events
    types:
      - created
      - completed

jobs:
  greeting:
    if: ${{ github.event_name == 'workflow_dispatch' }}  # Run only for manual triggers
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello, ${{ github.event.inputs.name }}!"

  schedule-log:
    if: ${{ github.event_name == 'schedule' }}  # Run only for scheduled events
    runs-on: ubuntu-latest
    steps:
      - name: Print Schedule Message
        run: echo "Scheduled workflow executed on $(date)."

  create-check-run:
    runs-on: ubuntu-latest
    steps:
      - name: Create a Check Run
        uses: actions/github-script@v6
        with:
          script: |
            const checkRun = await github.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: "CI Check", // Name of the check
              head_sha: context.sha, // The commit SHA this check corresponds to
              status: "in_progress", // Initial status of the check
            });
            console.log('Check run created:', checkRun.data.id);

  webhook-log:
    if: ${{ github.event_name == 'check_run' }}  # Run only for webhook events
    runs-on: ubuntu-latest
    steps:
      - name: Print Webhook Event
        run: |
          echo "Triggered by webhook event: ${{ github.event_name }}"
